[package]
name = "deepconvo-mindmap-tauri"
version = "1.0.0"
description = "BranchMark desktop application"
edition = "2021"
publish = false

[lib]
name = "deepconvo_mindmap_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
